# Form implementation generated from reading ui file 'demoVideoControls.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 589)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_video = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_video.setObjectName("label_video")
        self.verticalLayout.addWidget(self.label_video)
        self.videoSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.videoSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.videoSlider.setObjectName("videoSlider")
        self.verticalLayout.addWidget(self.videoSlider)
        self.pushButton_rewind_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_rewind_1.setObjectName("pushButton_rewind_1")
        self.verticalLayout.addWidget(self.pushButton_rewind_1)
        self.pushButton_rewind_chunk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_rewind_chunk.setObjectName("pushButton_rewind_chunk")
        self.verticalLayout.addWidget(self.pushButton_rewind_chunk)
        self.pushButton_forward_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_forward_1.setObjectName("pushButton_forward_1")
        self.verticalLayout.addWidget(self.pushButton_forward_1)
        self.pushButton_forward_chunk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_forward_chunk.setObjectName("pushButton_forward_chunk")
        self.verticalLayout.addWidget(self.pushButton_forward_chunk)
        self.pushButton_play = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_play.setObjectName("pushButton_play")
        self.verticalLayout.addWidget(self.pushButton_play)
        self.pushButton_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout.addWidget(self.pushButton_stop)
        self.pushButton_rewind_to_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_rewind_to_start.setObjectName("pushButton_rewind_to_start")
        self.verticalLayout.addWidget(self.pushButton_rewind_to_start)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_video.setText(_translate("MainWindow", "label for video"))
        self.pushButton_rewind_1.setText(_translate("MainWindow", "rewind 1"))
        self.pushButton_rewind_chunk.setText(_translate("MainWindow", "rewind chunk"))
        self.pushButton_forward_1.setText(_translate("MainWindow", "forward 1"))
        self.pushButton_forward_chunk.setText(_translate("MainWindow", "forward chunk"))
        self.pushButton_play.setText(_translate("MainWindow", "play"))
        self.pushButton_stop.setText(_translate("MainWindow", "stop"))
        self.pushButton_rewind_to_start.setText(_translate("MainWindow", "rewind to start"))
